- cyclonedx/cli/generateBom.py
This should prevent exceptions such as this one:
```
Traceback (most recent call last):
File "c:\python\python_3.7.4_64bit\Lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "c:\python\python_3.7.4_64bit\Lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Data\.virtualenvs\cycloneDX-fCyJ5Voc\Scripts\cyclonedx-py.exe\__main__.py", line 9, in <module>
File "c:\Data\.virtualenvs\cyclonedx-fcyj5voc\lib\site-packages\cyclonedx\cli\generateBom.py", line 140, in main
text_file.write(bom_xml)
File "c:\Data\.virtualenvs\cyclonedx-fcyj5voc\lib\encodings\cp1252.py", line 19, in encode
return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0103' in position 57206: character maps to …
```
> Enforced UTF-8 encoding while writing bom.xml

- cyclonedx/cli/generateBom.py
It's possible for the requirements.txt file to have local file listings.  These do not have 'name' values, and so cause a runtime error when trying to concatenate a NoneType with a string.  Test for 'local_file' requirements and skip them when generating bom.
See https://requirements-parser.readthedocs.io/en/latest/usage.html#parsing-requirement-specifiers
> Support requirements.txt with local files

- cyclonedx/cli/generateBom.py
Currently the BOM generation breaks when a single requirement does not refer to a specific version. It would be better to continue with the other requirements.
> Continue with other requirements

- .github/dependabot.yml
Move to v2 config which uses a config-file.
Signed-off-by: David Karlsen <david@davidkarlsen.com>
> Configure dependabot through config-files

- .github/workflows/release.yml
- Dockerfile
There was a race condition with how the Docker image was being built. It was installing it from PyPI without specifying a version. So if the package had been built and published, but hadn't been indexed yet the Docker image would have the previous version.
Changing the Dockerfile to copy in the locally built package instead.
> Use release built package when building Docker image

- cyclonedx/bom/reader.py
See https://github.com/CycloneDX/cyclonedx-python/issues/103
> Prevent crash when package_license is none from pypi null value

- cyclonedx/bom/generator.py
- cyclonedx/bom/reader.py
- cyclonedx/models/component.py
This will help to make reusing of code easier. For example, someone can import this library in their Python script and use these functions to generate an SBoM where components could be of different types in their use case.
> Make component type generic

- tests/resources/valid-metadata-timestamp-1.2.json
Included  4-spaces instead of 2-spaces, changed the "specVersion" to 1.2, corrected the value of timestamp and the ordering of metadata & components.
> Updated valid-metadata-timestamp-1.2.json

- cyclonedx/bom/reader.py
Hi,
requests.get call is used by the reader module to connect to pypi.org so metadata can be collected. In environments where HTTP proxies are used, above call fails to connect to pypi.org. 
In this PR, requests.get call is modified to use `proxies` argument if `HTTPS_PROXY` environment variable is set.
`proxies={'https':<HTTPS_PROXY>}`
This PR addresses #205
> Issue# 205. Use HTTPS_PROXY if env is set

- README.md
- cyclonedx_py/client.py
In response to #245.
This PR adds some error handling (to provide user feedback) and also will attempt to fallback to a known manifest filename for the following input types:
- Pip `Pipfile.lock`
- Poetry `poetry.lock`
- Requirements `requirements.txt`
These will only be found if in the current working directory.
A more informative error is provided if we fail to determine a source for input.
> FIX: Fallback to default manifest names in current directory when no `-i` supplied and nothing piped in via STDIN

- .github/workflows/ci.yml
- .gitignore
- .mypy.ini
- cyclonedx_py/client.py
- poetry.lock
- pyproject.toml
- tests/__init__.py
- tests/base.py
- tests/test_cyclonedx.py
- tox.ini
* bumped dependency `cyclonedx-python-lib` to ^0.11 - closes #254
* added static code analysis via `mypy` - closes #253
* added additional QA tools: `flake8-annotations`, & `flake8-bugbear`
* fixed tox to run with correct python versions
* added missing typehints
* made the unittests an own module
> static code analysis & general fixes

- CONTRIBUTING.md
- poetry.lock
- pyproject.toml
closes #275
bumped `cyclonedx-python-lib` to >=0.12.2 which loosened a lot of dependencies, so this PR was made possible.
update locked dependencies:
• Updating pycodestyle (2.7.0 -> 2.8.0)
• Updating pyflakes (2.3.1 -> 2.4.0)
• Updating flake8 (3.9.2 -> 4.0.1)
• Installing autopep8 (1.6.0)
• Updating flake8-annotations (2.0.1 -> 2.7.0)
> chore: update `flake8` to v4 and add `autopep8`

- .github/workflows/docker.yml
- .github/workflows/manual-release-candidate.yml
- .github/workflows/python.yml
- .github/workflows/release.yml
- pyproject.toml
currently working on several topics in parallel 
goals:
* fix a **BUG**:  on each push to master a new docker image is build and pushed to dockerhub, regardless if a semantic-release was issued or not. - see #292
* ~~encapsulate docker foo in a venv~~ - reverted due to https://github.com/CycloneDX/cyclonedx-python/pull/290#issuecomment-1013679750
* have docker image generate own SBOM - prep for #289
* split release: PyPI release separate from docker release -- compare to https://github.com/CycloneDX/cyclonedx-node-module/blob/master/.github/workflows/release.yml
* this looks impossible at first, as the `python semantic release` action does not have proper outputs, yet. 
requested via https://github.com/relekang/python-semantic-release/issues/401
* actually it is not impossible to detect …
> chore: improve docker, release, docs 

- README.md
- cyclonedx_py/client.py
Bind reading from stdin on specifying `-i -`. This is part of
[`argparse.FileType`](https://docs.python.org/3/library/argparse.html?highlight=pseudo-argument#argparse.FileType).
Fixes #306
Local tests under the following conditions:
* implicit reading `poetry.lock` using args `-p -o -`
* explicit reading `poetry.lock` using args `-p -i poetry.lock -o -`
* explicit reading `poetry.lock` file after renaming using
`cat p.lock | python -m cyclonedx_py.client -p -i - -o -`
Signed-off-by: Theodor van Nahl <theo@van-nahl.org>
> fix: properly support reading from stdin

- .github/workflows/release.yml
> fix: docker image releae checkout ref w/o `tags`

- cyclonedx_py/py.typed
- poetry.lock
- pyproject.toml
Signed-off-by: Paul Horton <paul.horton@owasp.org>
Closes #312
> feat: added marker and classifiers to denote this as typed

- cyclonedx_py/parser/poetry.py
- cyclonedx_py/parser/requirements.py
- docs/usage.rst
- poetry.lock
- pyproject.toml
- tests/fixtures/requirements-local-and-remote-packages.txt
- tests/fixtures/requirements-local-packages.txt
- tests/fixtures/requirements-nested.txt
- tests/fixtures/requirements-private-packages.txt
- tests/fixtures/requirements-with-urls.txt
- tests/test_parser_requirements.py
In this PR, I replaced the `pkg_resources` from `setuptools` with [`pip-requirements-parser`](https://github.com/nexB/pip-requirements-parser). This change helps with better parsing of `requirements.txt` files because it supports local files, private repositories, hashes, and possibly other features. which I haven't looked into or tested. This PR tries to address the PRs mentioned in this discussion: https://github.com/CycloneDX/cyclonedx-python/discussions/319.
As you might have noticed by now from the commits, these are the changes I made:
1. Revamped the `RequirementsParser` class:
- It now accepts path or file content.
- Name of the package will be either the actual name or the URL, including file paths.
- Version will be either the pinned version of the package or a list of versions …
> feat: Change requirements parser

- CONTRIBUTING.md
- README.md
added/fixed some links to the docs in RTFD
reminder: the short form for `readthedocs` is `RTFD` - like in https://rtfd.io
> docs: add and fix hint to rtfd

- cyclonedx_py/utils/conda.py
- tests/fixtures/conda-list-broken.txt
- tests/fixtures/conda-list-build-number-text.txt
- tests/test_parser_conda.py
- tests/test_utils_conda.py
conda packacge string parser no longer raises unexpected errors, 
if the build-number is non-numeric.
fixes #331
> fix(conda-parser): build-number recognition for non-numerics

- cyclonedx_py/__main__.py
- cyclonedx_py/client.py
- docs/usage.rst
- tests/integration/__init__.py
- tests/integration/test_can_call_module.py
> feat: make package/module callable

- cyclonedx_py/parser/pipenv.py
- tests/test_parser_pipenv.py
Signed-off-by: sleightsec <69399725+sleightsec@users.noreply.github.com>
fixes #347
> remove index=pypi attribute requirement for pipenv hash inclusion

- cyclonedx_py/parser/conda.py
- cyclonedx_py/utils/conda.py
- tests/test_parser_conda.py
- tests/test_utils_conda.py
Add conda_package_to_purl() utility function
Add package_format field to CondaPackage
purl specification can be found here: https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#conda
Fixes #357
> Update Conda purl to match specification

- poetry.lock
part of #355
WIP :construction:
> chore: Bump cyclonedx-python-lib from 2.4.0 to 2.5.2

- README.md
- cyclonedx_py/client.py
- cyclonedx_py/parser/conda.py
- cyclonedx_py/parser/environment.py
- cyclonedx_py/parser/pipenv.py
- cyclonedx_py/parser/poetry.py
- cyclonedx_py/parser/requirements.py
- tests/test_parser_conda.py
- tests/test_parser_environment.py
- tests/test_parser_pipenv.py
- tests/test_parser_poetry.py
- tests/test_parser_requirements.py
Partially addresses https://github.com/CycloneDX/cyclonedx-python/issues/355.
Add CLI argument to use purl.to_string() as bom_ref for Components. This should improve reproducibility.
> feat: set Component `bom_ref` to match `purl`

- CONTRIBUTING.md
- docs/usage.rst
Hello,
This is just a small PR for a couple of documentation updates:
- I ran across a doc typo in the poetry usage instructions, for the [pyproject.toml](https://python-poetry.org/docs/pyproject/) file. 
- And in the contribution guidelines, I updated the [flag](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) for signing off on commits.
Thanks!
> docs: Minor updates to poetry usage details & contributing.md

- Dockerfile
- README.md
- cyclonedx_py/client.py
- docs/usage.rst
- pyproject.toml
> docs: describe `cyclonedx-py` rather than `cyclonedx-bom`

- cyclonedx_py/parser/environment.py
- tests/test_parser_environment.py
current implementation uses SPDX license expressions for everything, instead of using license with name or wth spdx ids
this caused broken results.
better: use license with name for everything, as this cannot cause any malformed result.
Here is the fix.
closes #410
> fix: properly declare licenses from environment

- cyclonedx_py/parser/environment.py
- tests/test_parser_environment.py
The classifier parser did not work as expected on my machine.
In python3.8 and python3.9 the type `email.message import Message` is used as metadata type and the metadata are stored in `i_metadata._headers` as a list of tuples. To iterate over the classifiers in this list of tuples 
```
for classifier in i_metadata['Classifier']:
```
was used. Though this loop iterates only over the first classifiers characters and not over all classifiers, so the classifiers were never parsed.
I propose in this commit to generate a list of classifiers for python3.8/python3.9 and python3.10 separately and loop over the list of classifiers.
Please note:
I created this PR on github web, I guess the commit message needs to be adjusted before merging!
> Fix classifier parsing in python 3.8 / python 3.9

- poetry.lock
- pyproject.toml
currently locked version of coverage would not be compatible to py311.
see https://github.com/CycloneDX/cyclonedx-python/pull/437#issuecomment-1309867925
therefore, it gets bumped
> chore(dep): bump and devide `coverage`

- README.md
- cyclonedx_py/client.py
- docs/usage.rst
I was reading the README and noticed some missing spaces. Hope it's useful.
> fix: add a missing space in the help pages `pathto` -> `path to`

- .github/workflows/docker.yml
docker images under test failed, they installed wrong or outdated versions.
To mitigate, a more unique version identifier was chosen.
> ci: test dockerimage fix

- poetry.lock
- pyproject.toml
- requirements.lowest.txt
bump `pip-requirements-parser` 31.2 -> 32.0
fixes #449
> fix: adjust dependency `pip-requirements-parser` to a working version

- .github/workflows/docker.yml
- cyclonedx_py/client.py
- cyclonedx_py/parser/_debug.py
- cyclonedx_py/parser/conda.py
- cyclonedx_py/parser/environment.py
- cyclonedx_py/parser/pipenv.py
- cyclonedx_py/parser/poetry.py
- cyclonedx_py/parser/requirements.py
- poetry.lock
- pyproject.toml
currently the parsers do not output any debug information.
this PR will make all parser verbose on demand. 
call `cyclonedx-bom -X` for testing.
fixes #461
> feat: parsers can outbut more debug messages

- CONTRIBUTING.md
There's a difference between signing commits (-S) and signing off commits (-s).
cross-port of CycloneDX/cyclonedx-python-lib/pull/319
> docs: improve CONTRIBUTION instructions - sign-off step

- cyclonedx_py/utils/conda.py
- tests/fixtures/conda-list-issue462.json
- tests/test_parser_conda.py
Proposed fix for https://github.com/CycloneDX/cyclonedx-python/issues/462.
When generating the purl, check for "conda" packages with pseudo channel and platform "pypi". Those are actually pip-installed packages in the conda environment. Generate a `pgk:pypi` purl for them.
> fix: PURL for PyPI packages from 'conda list' have the correct format now

- cyclonedx_py/client.py
- pyproject.toml
in prep for #488
followup of #415
> feat: deprecated CLI command `cyclonedx-bom` prints deprecation warning on STDERR before execution

- CONTRIBUTING.md
- poetry.lock
- pyproject.toml
chore: removed `autopep8` in favour of `flake8`
Fixes:
- #500 
Resolves:
- #509 
- #476 
- #457 
- #455
> chore: bumped dev dependenices

- docs/usage.rst
- pyproject.toml
> BREAKING CHANGE: remove deprecated `cyclonedx-bom` command #488

- .github/workflows/python.yml
tests on windows have issues caused by `virtualenv`<=20.21 as a dependency from `tox`
see https://github.com/CycloneDX/cyclonedx-python/actions/runs/5534372036
> ci: disable windows tests on py>=3.8

- README.md
- cyclonedx_py/client.py
- cyclonedx_py/utils/conda.py
- docs/usage.rst
> fix: fix typo in help page

- .github/workflows/docker.yml
- .github/workflows/python.yml
- .github/workflows/release.yml
somebody renamed the `master` branch to `main`.
but forgot to transition the CI triggers.
fixed this
> ci: finish transition to main branch

- pyproject.toml
somebody renamed the `master` branch to `main`.
but forgot to transition the CI triggers.
fixed this
> chore: finish transition to main branch

- README.md
somebody renamed the `master` branch to `main`.
but forgot to transition the docs.
fixed this
> fix: referenced branch `main`, instead of `master`

- CONTRIBUTING.md
- cyclonedx_py/_internal/__init__.py
- cyclonedx_py/_internal/license_trove_classifier.py
- cyclonedx_py/_internal/trove_classifier_license.py
- cyclonedx_py/parser/environment.py
- tests/test_parser_environment.py
> feat: environment licenses as proper SPDX

- .github/workflows/docker.yml
- .github/workflows/manual-release-candidate.yml
- .github/workflows/python.yml
- .github/workflows/release.yml
- cyclonedx_py/client.py
- cyclonedx_py/parser/environment.py
- cyclonedx_py/utils/conda.py
- deps.lowest.r
- poetry.lock
- pyproject.toml
- tox.ini
- BREAKING CHANGE: remove support for py37 and below
- removed now unnecessary dependencies
fixes #582
> BC: drop support for python <= 3.7

- README.md
- cyclonedx_py/__init__.py
- cyclonedx_py/client.py
- docs/conf.py
- pyproject.toml
adds `--version` CLI switch, which causes the output of the current version.
fixes #583
> feat: have own version visible everywhere

- cyclonedx_py/client.py
The custom input specified via CLI's `-i` option did not properly detect the input encoding.  
This was fixed.
> fix: custom input encoding

- .github/ISSUE_TEMPLATE/ValidationError-report.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- README.md
- cyclonedx_py/client.py
- docs/usage.rst
- poetry.lock
- tests/integration/test_can_call_module.py
validation output
- CLI switches
- documentation
- implementation
- special github issue templates for the purpose
> feat: validate output

- .github/workflows/docker.yml
- .github/workflows/release.yml
- CHANGELOG.md
- cyclonedx_py/__init__.py
- docs/conf.py
- pyproject.toml
> feat: publish to GHCR

- .github/workflows/docker.yml
- .github/workflows/python.yml
- .github/workflows/release.yml
supersedes #625 
supersedes #624
> ci: modernize artifact action

- tox.ini
our sdist config ships tests and docs.
when you have a lot of venvs laying around in the `tests` or `docs` flder, then `poetry build -f sdist` crashes ... a known bug of poetry ... 
per default, tox installs in sdist mode .... 
this causes issues locally, ... which is annoying. 
here is a workaround: dont build sdist, build wheel only.
> chore: run tox w/o sdist

- README.md
- cyclonedx_py/_internal/cli.py
- cyclonedx_py/_internal/poetry.py
- docs/usage.rst
- tests/integration/test_cli_environment.py
> feat: subcommand `environment` got aliases `env`, `venv`

- pyproject.toml
- tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock20_1.0.xml.bin
- tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock20_1.1.xml.bin
- tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock20_1.2.json.bin
- tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock20_1.2.xml.bin
- tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock20_1.3.json.bin
- tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock20_1.3.xml.bin
- tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock20_1.4.json.bin
- tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock20_1.4.xml.bin
- tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock20_1.5.json.bin
- tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock20_1.5.xml.bin
- tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock20_1.6.json.bin
- tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock20_1.6.xml.bin
- tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock21_1.0.xml.bin
- tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock21_1.1.xml.bin
- tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock21_1.2.json.bin
- tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock21_1.2.xml.bin
- tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock21_1.3.json.bin
- tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock21_1.3.xml.bin
- tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock21_1.4.json.bin
- tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock21_1.4.xml.bin
- tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock21_1.5.json.bin
- tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock21_1.5.xml.bin
- tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock21_1.6.json.bin
- tests/_data/snapshots/poetry/plain_multi-constraint-deps_lock21_1.6.xml.bin
`cyclonedx-python-lib` v9 was released.
the breaking changes do not cause any any friction in the usage here, so let's add support for it.
> feat: add support for `cyclonedx-python-lib>=9.0<10`

- cyclonedx_py/_internal/cli.py
- docs/usage.rst
- tests/unit/test_cli.py
> feat: deprecate CLI switch `--schema-version`; use new `--spec-version` instead

- cyclonedx_py/_internal/cli.py
- docs/usage.rst
- tests/integration/test_cli_environment.py
- tests/integration/test_cli_pipenv.py
- tests/integration/test_cli_poetry.py
- tests/integration/test_cli_requirements.py
- tests/unit/test_cli.py
> feat: deprecate CLI switch `--outfile`; use new `--output-file` instead

- cyclonedx_py/_internal/utils/mimetypes.py
Add a mimetype for the Rich Text Format (RTF).
The format is 7-Bit ASCII safe, so automatically passes basic checks for UTF-8. But with all its custom tags and escape sequences it formally is closer to a binary format. 
So we use the application/rtf mimetype instead of the also possible text/rtf mimetype, as most consumers will consider this to be binary.
This overrides the misdetection by the stdlib, which claims RTF to be associated with application/msword.
> feat: Add mimetype detection for rich text format (rtf)

- Dockerfile
As per [OWASP's Docker Security Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html), it is recommended to set a user instead of running the container as root.
```bash
virgo@lenovo:~$ docker ps -a
CONTAINER ID   IMAGE                 COMMAND       CREATED              STATUS              PORTS     NAMES
ee568549229f   cyclonedx-py:latest   "/bin/bash"   About a minute ago   Up About a minute             nifty_swirles
virgo@lenovo:~$ docker exec -it ee568549229f sh -c "id"
uid=1000(cyclonedx) gid=1000(cyclonedx) groups=1000(cyclonedx)
```
:arrow_up: Now the container is running as a standard user.
> feat: rootless docker container

- .github/workflows/python.yml
- CONTRIBUTING.md
- cyclonedx_py/_internal/cli.py
- cyclonedx_py/_internal/pipenv.py
- cyclonedx_py/_internal/poetry.py
- cyclonedx_py/_internal/utils/pyproject.py
- pyproject.toml
- tests/__init__.py
- tox.ini
- bring tool `pyupgrade`, tests and such 
- apply latest code style
> chore: bring pyupgrade

- cyclonedx_py/_internal/cli.py
- docs/usage.rst
> feat!: remove deprecated CLI switches `--schema-version` and `--outfile`, use `--spec-version` and `--output-file` instead
