- cyclonedx/cli/generateBom.py
- requirements.txt
- setup.py
> Support PEP 440 concepts like pre, post, and development versions

- cyclonedx/cli/generateBom.py
If a package version is not found in PyPi, create an entry
for that version and print a warning to the console.
> Handle package versions not found in PyPi

- cyclonedx/cli/generateBom.py
- requirements.txt
Added encoding detection using chardet. Fixes #20
> Encoding detection added

- Dockerfile
Signed-off-by: David Karlsen <david@davidkarlsen.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cyclonedx/cyclonedx-python/46)
> Docker image. Fixes #45

- .gitignore
- README.rst
- cyclonedx/bom/generator.py
- cyclonedx/bom/reader.py
- cyclonedx/bom/validator.py
- cyclonedx/client.py
- cyclonedx/models/__init__.py
- cyclonedx/models/component.py
- cyclonedx/models/component_license.py
- cyclonedx/models/hash.py
- cyclonedx/models/license.py
- cyclonedx/schema/bom-1.2.json
- cyclonedx/schema/bom-1.2.schema.json
- requirements.txt
- setup.py
- tests/resources/bom.json
- tests/resources/bom.xml
- tests/test_cyclonedx.py
Adds support for JSON output and fix bug that causes duplicate components to be listed in the BOM.
> Support for JSON output

- .github/dependabot.yml
Fixes error at: https://github.com/CycloneDX/cyclonedx-python/runs/1083248979
> fix language definition

- cyclonedx/bom/reader.py
removed a duplicate function call
> remove duplicate function call

- tests/resources/valid-metadata-timestamp-1.2.xml
Included encoding attribute in the header of XML
> Updated valid-metadata-timestamp-1.2.xml

- tests/test_metadata.py
> Updated test_metadata.py

- cyclonedx/bom/generator.py
- tests/resources/invalid-xml-characters/bom.xml
- tests/resources/invalid-xml-characters/requirements.txt
- tests/test_cyclonedx.py
> Fix for invalid xml characters

- cyclonedx_py/client.py
- tests/test_cyclonedx.py
Fix to resolve issue reported in #230.
This now defaults to `requirements.txt` in the current directory.
Signed-off-by: Paul Horton <phorton@sonatype.com>
> Fix for hang when no `-rf` flag supplied with `-r` flag

- .github/workflows/release.yml
- Dockerfile
> FIX: Re-enable build and publish of Docker Image

- .github/workflows/release.yml
> gh-action release use org's secrets

- .gitignore
- .readthedocs.yaml
- docs/Makefile
- docs/conf.py
- docs/index.rst
- docs/install.rst
- docs/make.bat
- docs/requirements.txt
- docs/support.rst
- docs/usage.rst
Signed-off-by: Paul Horton <phorton@sonatype.com>
Closes: #295
> doc: migration to RTD

- README.md
- cyclonedx_py/__init__.py
- cyclonedx_py/client.py
- cyclonedx_py/parser/__init__.py
- cyclonedx_py/parser/conda.py
- cyclonedx_py/parser/environment.py
- cyclonedx_py/parser/pipenv.py
- cyclonedx_py/parser/poetry.py
- cyclonedx_py/py.typed
- cyclonedx_py/utils/__init__.py
- poetry.lock
- pyproject.toml
- tests/test_parser_conda.py
- tests/test_parser_environment.py
- tests/test_parser_pipenv.py
- tests/test_parser_poetry.py
- tests/test_parser_requirements.py
Signed-off-by: Paul Horton <paul.horton@owasp.org>
Closes: 
- #310 
- #312 
**Update: ** This will be considered a breaking change due to https://github.com/CycloneDX/cyclonedx-python-lib/issues/163 being indirectly included.
> BREAKING CHANGE: update to latest RC of `cyclonedx-python-lib`

- poetry.lock
- pyproject.toml
BREAKING CHANGE: Default Schema Version has been replaced by notion of LATEST supported Schema Version
Signed-off-by: Paul Horton <paul.horton@owasp.org>
> feat: bump to latest `cyclonedx-python-lib`

- .isort.cfg
- CONTRIBUTING.md
- cyclonedx_py/client.py
- cyclonedx_py/parser/conda.py
- cyclonedx_py/parser/environment.py
- cyclonedx_py/parser/pipenv.py
- cyclonedx_py/parser/poetry.py
- cyclonedx_py/parser/requirements.py
- cyclonedx_py/utils/conda.py
- poetry.lock
- pyproject.toml
- tests/test_parser_conda.py
- tests/test_parser_environment.py
- tests/test_parser_pipenv.py
- tests/test_parser_poetry.py
- tests/test_parser_requirements.py
- tests/test_utils_conda.py
- tox.ini
fixes #274
* added QA tool: `isort`
* added QA tests: `flake8-isort`
* applied `isort` to all code, so  imports are sorted
> style: sort imports

- cyclonedx_py/client.py
> fix: cli default file for json format

- .github/workflows/python.yml
- cyclonedx_py/client.py
- poetry.lock
- pyproject.toml
- requirements.lowest.txt
- tox.ini
* fix: add actively used (transitive) dependencies
* ci: add test with lowest dependencies
caused by https://github.com/CycloneDX/cyclonedx-python/pull/361#pullrequestreview-993082726
> fix: add actively used (transitive) dependencies

- cyclonedx_py/parser/conda.py
- tests/test_parser_conda.py
> Add Conda MD5 hash to Component.hashes, if available

- tox.ini
> chore: fix poetry in tox

- cyclonedx_py/client.py
Signed-off-by: a1lu <github.foreshoe@slmail.me>
> feat: Pass purl-bom-ref to EnvironmentParser

- cyclonedx_py/parser/environment.py
> fix: ignore broken licenses in `environment` parser

- cyclonedx_py/client.py
> feat: error- and debug-output is send to STDERR, instead of STDOUT

- requirements.lowest.txt
fixes #497
fixes #498 
closes #495
> chore: fix lowest requirements for tests

- constraints.lowest.txt
- pyproject.toml
- tox.ini
> chore: adjust lowest constraints/requirements

- deps.lowest.r
- pyproject.toml
- tox.ini
> chore: rename file for lowest constraints/requirements

- deps.lowest.r
- poetry.lock
- pyproject.toml
> feat: use `cyclonedx-python-lib` `4.0.0`

- .github/workflows/python.yml
- CONTRIBUTING.md
- cyclonedx_py/client.py
- poetry.lock
- pyproject.toml
- tox.ini
> chore: bump devtools py38

- poetry.lock
- pyproject.toml
fixes https://github.com/CycloneDX/cyclonedx-python/issues/598
> chore{deps}: bump cyclonedx-python-lib

- cyclonedx_py/_internal/environment.py
- docs/usage.rst
https://github.com/CycloneDX/cyclonedx-python/issues/689 made it visible that some parts of the docs were not clear enough.
this PR tries to improve the situation.
> docs: imprve `environment` use cases and examples

- .github/workflows/docker.yml
- .github/workflows/python.yml
- .github/workflows/release.yml
- Dockerfile
> ci: default to python 3.12

- cyclonedx_py/_internal/utils/pep610.py
- tests/_data/infiles/environment/with-urls/init.py
- tests/_data/snapshots/environment/plain_with-urls_1.0.xml.bin
- tests/_data/snapshots/environment/plain_with-urls_1.1.xml.bin
- tests/_data/snapshots/environment/plain_with-urls_1.2.json.bin
- tests/_data/snapshots/environment/plain_with-urls_1.2.xml.bin
- tests/_data/snapshots/environment/plain_with-urls_1.3.json.bin
- tests/_data/snapshots/environment/plain_with-urls_1.3.xml.bin
- tests/_data/snapshots/environment/plain_with-urls_1.4.json.bin
- tests/_data/snapshots/environment/plain_with-urls_1.4.xml.bin
- tests/_data/snapshots/environment/plain_with-urls_1.5.json.bin
- tests/_data/snapshots/environment/plain_with-urls_1.5.xml.bin
> fix: more resilent PEP610 parsing

- .github/workflows/release.yml
- CHANGELOG.md
- cyclonedx_py/__init__.py
- docs/conf.py
- pyproject.toml
> chore: trusted publishing
